### ISSUE TITLE
On rotate the slider is not updated right

### ISSUE THREAD

**Issue by MDalprato** [maximbilan/SwiftlySlider#1]
I noticed that if you rotate the device with Auto-layout set on the slider, the view is not updated.
This will cause issues like: the rounder edges are not rounder anymore and the slider image is bigger then expected.

Solution:

Add "self.setNeedsDisplay()" at the end of "func update()".

Marco

**Comment by maximbilan** [comment]
Thanks.
You can create pull request with your fix and I will approve.
